name: asr_reveal
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.11=h7f8727e_2
  - pip=23.3=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.24.1
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - alembic==1.12.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - audioread==3.0.1
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - bleach==6.1.0
    - blinker==1.7.0
    - cachetools==5.3.2
    - certifi==2023.7.22
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorlog==6.7.0
    - comm==0.1.4
    - contourpy==1.1.1
    - cycler==0.12.1
    - datasets==2.15.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.7
    - dnspython==2.4.2
    - evaluate==0.4.1
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - fastjsonschema==2.18.1
    - filelock==3.13.1
    - flask==3.0.0
    - fonttools==4.43.1
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - future==0.18.3
    - google-auth==2.23.4
    - google-auth-oauthlib==1.1.0
    - greenlet==3.0.1
    - grpcio==1.59.2
    - huggingface-hub==0.19.4
    - hydra-configs-pytorch-lightning==0.1.0
    - hydra-core==1.3.2
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - ipykernel==6.26.0
    - ipython==8.17.2
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.2
    - jiwer==3.0.3
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.5.0
    - jupyter-console==6.6.3
    - jupyter-core==5.5.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.9.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.7
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - levenshtein==0.23.0
    - librosa==0.10.1
    - lightning-utilities==0.9.0
    - llvmlite==0.41.1
    - mako==1.2.4
    - markdown==3.5.1
    - markupsafe==2.1.3
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - multiprocess==0.70.15
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - numba==0.58.1
    - numpy==1.26.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.52
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - optuna==3.4.0
    - overrides==7.4.0
    - packaging==23.2
    - pandas==2.1.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pillow==10.1.0
    - platformdirs==3.11.0
    - pluggy==1.3.0
    - pooch==1.8.0
    - prometheus-client==0.18.0
    - prompt-toolkit==3.0.39
    - protobuf==4.23.4
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==14.0.1
    - pyarrow-hotfix==0.6
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydeprecate==0.3.1
    - pygments==2.16.1
    - pyparsing==3.1.1
    - pytest==7.4.3
    - python-dateutil==2.8.2
    - python-etcd==0.4.5
    - python-json-logger==2.0.7
    - python-levenshtein==0.23.0
    - pytorch-lightning==1.5.0
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - qtconsole==5.4.4
    - qtpy==2.4.1
    - rapidfuzz==3.5.1
    - referencing==0.30.2
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - rsa==4.9
    - safetensors==0.4.1
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soundfile==0.12.1
    - soupsieve==2.5
    - sox==1.4.1
    - soxr==0.3.7
    - sqlalchemy==2.0.22
    - stack-data==0.6.3
    - sympy==1.12
    - tensorboard==2.15.0
    - tensorboard-data-server==0.7.2
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tokenizers==0.15.0
    - tomli==2.0.1
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchelastic==0.2.2
    - torchmetrics==1.2.0
    - torchvision==0.14.0
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.13.0
    - transformers==4.35.2
    - triton==2.1.0
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - urllib3==2.0.7
    - wcwidth==0.2.9
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - werkzeug==3.0.1
    - wget==3.2
    - widgetsnbextension==4.0.9
    - xxhash==3.4.1
    - yarl==1.9.2
    - zipp==3.17.0
prefix: /scratch/f006pq6/bin/miniconda3/envs/asr_reveal
